function PGMS()
global A u f a DirName FileMask c
UP = userpath();
s=[UP(1:end-1) '/PGMS.set.mat'];
if exist(s) == 2 %#ok
     load(s,'DirName','FileMask');
end
if isempty(A)
    LoadDir(pwd)
end
if isempty(DirName)
    DirName = pwd;
end
% d = dir([DirName '/' FileMask ]);
% A = d;
s2 = horzcat(DirName, '\', strrep(FileMask, '*', ''), '.mat');
% size(s)
% display(s);
if exist(s2) == 2 %#ok;
    load(s2);
end
f(1).fid = figure();
SX = 0.7;
SY = 0.1;
sx = SY/8;
sy = SY/8;
% c=zeros(2,8);
u(1).String={A.name};
u(1).Callback=@PlotData;
u(2).Callback=@LoadDir;
u(4).Callback=@LimData;
for x=1:2
    for y=1:8
        c(y,x).uid = uicontrol('Parent',f(1).fid,'Style','CheckBox',...
            'Unit','Normalized','Callback',u(1).Callback,...
            'Position',[SX+sx*(x-1) SY-y*sy sx sy]);
    end    
end
u(1).uid = uicontrol('Parent',f(1).fid, 'Style', 'listbox', ...
    'String', u(1).String','Units','Normalized',...
    'Position', [0 .3 .2 .7],'Callback',u(1).Callback,...
    'Max', 2);
u(2).uid = uicontrol('Parent', f(1).fid,'Units','Normalized',...
    'Position', [0 0 .2 .1],'Callback',u(2).Callback,...
    'String','');
u(3).uid = uicontrol('Parent',f(1).fid, 'Style', 'listbox', ...
    'String','','Units','Normalized',...
    'Position', [0 .1 .2 .2],'Max',6,...
    'Callback',u(1).Callback,'Value',[1 2 3]);
a(1).aid = axes('Parent', f(1).fid, 'Units', 'Normalized', ...
    'Position', [0.25 0.15 0.7 0.8]);
u(4).uid = uicontrol('Parent',f(1).fid, 'Style', 'slider', ...
    'Units','Normalized','Position', [0.3 .075 .3 .025],...
    'Value',0,'Callback',u(4).Callback,'CreateFcn',u(1).Callback);
u(5).uid = uicontrol('Parent',f(1).fid, 'Style', 'slider', ...
    'Units','Normalized','Position', [0.3 .050 .3 .025],...
    'Value',1,'Callback',u(4).Callback);
u(6).uid = uicontrol('Parent',f(1).fid, 'Style', 'slider', ...
    'Units','Normalized','Position', [0.3 .025 .3 .025],...
    'Value',0,'Callback',u(4).Callback);
u(7).uid = uicontrol('Parent',f(1).fid, 'Style', 'slider', ...
    'Units','Normalized','Position', [0.3 .000 .3 .025],...
    'Value',1,'Callback',u(4).Callback);
u(8).uid = uicontrol('Parent',f(1).fid, 'Style', 'edit', ...
    'Units','Normalized','Position', [0.2 .05 .1 .05],...
    'String',0,'Callback',u(4).Callback);
u(9).uid = uicontrol('Parent',f(1).fid, 'Style', 'edit', ...
    'Units','Normalized','Position', [0.6 .05 .1 .05],...
    'String',1);
u(10).uid = uicontrol('Parent',f(1).fid, 'Style', 'edit', ...
    'Units','Normalized','Position', [0.2 .00 .1 .05],...
    'String',0);
u(11).uid = uicontrol('Parent',f(1).fid, 'Style', 'edit', ...
    'Units','Normalized','Position', [0.6 .00 .1 .05],...
    'String',1);
end